### ISSUE TITLE
Project TODO/Roadmap

### ISSUE THREAD

**Issue by maranomynet** [maranomynet/fridagar-node#1]
- [ ] Convert all code to typescript using esm exports
- [ ] Add more tests
- [ ] Rewrite README.md to properly describe the package
  - [ ] Mention that bun is used for development of the package.
  - [ ] Mention the old `fridagar` module
- [ ] Move the changelog into its own file
- [ ] Rename to `holidays-is`
- [ ] Add build.ts that runs tsc to emit both esm and cjs builds
- [ ] Add pkg.exports field
- [ ] Add `.npmignore` file
- [ ] Publish on npmjs.com
  - [ ] Maybe: Start by publishing all older versions for completeness.

**Comment by maranomynet** [comment]
Ugh, All todos are checked, except the "hopefully not" ones.

I'd really, really like to **not** publish this as a new library.

I'm going to wait for a few days more, in the hope I get some feedback regarding [this](https://github.com/gaui/fridagar-node/pull/10#issuecomment-1681183118).
